-- MySQL Script generated by MySQL Workbench
-- Tue Nov 28 16:40:45 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`offices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`offices` (
  `idoffices` INT NOT NULL AUTO_INCREMENT,
  `location` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idoffices`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `idusers` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employees` (
  `idemployees` INT NOT NULL AUTO_INCREMENT,
  `namel` VARCHAR(45) NOT NULL,
  `employee_type` VARCHAR(45) NOT NULL,
  `users_idusers` INT NOT NULL,
  PRIMARY KEY (`idemployees`),
  INDEX `fk_employees_users1_idx` (`users_idusers` ASC) VISIBLE,
  CONSTRAINT `fk_employees_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `mydb`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `idcustomer` INT NOT NULL AUTO_INCREMENT,
  `users_idusers` INT NOT NULL,
  PRIMARY KEY (`idcustomer`),
  INDEX `fk_customer_users1_idx` (`users_idusers` ASC) VISIBLE,
  CONSTRAINT `fk_customer_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `mydb`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order_history` (
  `idorder_history` INT NOT NULL,
  `customer_idcustomer` INT NOT NULL,
  PRIMARY KEY (`idorder_history`),
  INDEX `fk_orders_customer1_idx` (`customer_idcustomer` ASC) VISIBLE,
  CONSTRAINT `fk_orders_customer1`
    FOREIGN KEY (`customer_idcustomer`)
    REFERENCES `mydb`.`customer` (`idcustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orders` (
  `idorders` INT NOT NULL,
  `senders_name` VARCHAR(45) NOT NULL,
  `recipients_name` VARCHAR(45) NOT NULL,
  `delivery_type` VARCHAR(45) NOT NULL,
  `delivery_adress` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `offices_idoffices` INT NULL,
  `employees_idemployees` INT NOT NULL,
  `order_history_idorder_history` INT NOT NULL,
  PRIMARY KEY (`idorders`),
  INDEX `fk_packages_offices1_idx` (`offices_idoffices` ASC) VISIBLE,
  INDEX `fk_packages_employees1_idx` (`employees_idemployees` ASC) VISIBLE,
  INDEX `fk_orders_order_history1_idx` (`order_history_idorder_history` ASC) VISIBLE,
  CONSTRAINT `fk_packages_offices1`
    FOREIGN KEY (`offices_idoffices`)
    REFERENCES `mydb`.`offices` (`idoffices`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_packages_employees1`
    FOREIGN KEY (`employees_idemployees`)
    REFERENCES `mydb`.`employees` (`idemployees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_order_history1`
    FOREIGN KEY (`order_history_idorder_history`)
    REFERENCES `mydb`.`order_history` (`idorder_history`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`offices_has_employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`offices_has_employees` (
  `offices_idoffices` INT NOT NULL,
  `employees_idemployees` INT NOT NULL,
  PRIMARY KEY (`employees_idemployees`, `offices_idoffices`),
  INDEX `fk_offices_has_employees_employees1_idx` (`employees_idemployees` ASC) VISIBLE,
  INDEX `fk_offices_has_employees_offices1_idx` (`offices_idoffices` ASC) VISIBLE,
  CONSTRAINT `fk_offices_has_employees_offices1`
    FOREIGN KEY (`offices_idoffices`)
    REFERENCES `mydb`.`offices` (`idoffices`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offices_has_employees_employees1`
    FOREIGN KEY (`employees_idemployees`)
    REFERENCES `mydb`.`employees` (`idemployees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`packages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`packages` (
  `idpackages` INT NOT NULL,
  `weight` VARCHAR(45) NOT NULL,
  `orders_idorders` INT NOT NULL,
  PRIMARY KEY (`idpackages`),
  INDEX `fk_packages_orders1_idx` (`orders_idorders` ASC) VISIBLE,
  CONSTRAINT `fk_packages_orders1`
    FOREIGN KEY (`orders_idorders`)
    REFERENCES `mydb`.`orders` (`idorders`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
